---
- name: Update and Restart Synology NAS
  hosts: all
  become: true
  tasks:

    - name: Check for updates
      command: /usr/syno/sbin/synoupgrade --check
      register: update_check
      ignore_errors: true
      changed_when: false

    - name: Set fact for update_check success
      set_fact:
        update_check_success: "{{ update_check.rc == 0 }}"
      changed_when: false

    - name: Parse update availability from command output
      set_fact:
        update_json: "{{ update_check.stdout | regex_replace('UPGRADE_CHECKNEWDSM\\n', '') | from_json }}"
      when: 
        - update_check_success
        - update_check.stdout is search("Result")

    - name: Set update availability to true or false
      set_fact:
        update_available: "{{ update_json.available }}"
      when: 
        - update_check_success
        - update_check.stdout is search("Result")

    - name: Start the update if available
      command: /usr/syno/sbin/synoupgrade --start-force
      when: update_available | default(false) | bool
      register: update_started
      ignore_errors: true

    - name: Wait for Synology to restart (if it updated)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 600
      when: update_started is defined and update_started.changed