---
- name: Update and Restart Synology NAS
  hosts: all
  tasks:
    - name: Check for updates
      command: /usr/syno/sbin/synoupgrade --check
      register: update_check
      changed_when: false  # This ensures Ansible doesn't report a change for this task

    - name: Start the update if available
      command: /usr/syno/sbin/synoupgrade --start-force
      when: "'update is available' in update_check.stdout"  # Modify this condition based on the actual output of the check command
      register: update_started

    - name: Wait for Synology to restart (if it updated)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22  # or whatever port you're using for SSH
        delay: 60  # wait 60 seconds before starting to poll
        timeout: 600  # wait a maximum of 10 minutes for the NAS to come back online
      when: update_started is changed

    - name: Reboot Synology for good measure (only if update was started)
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true
      when: update_started is changed
