---
- name: Update and Restart Synology NAS
  hosts: all
  become: true
  tasks:
  
    - name: Check for updates
      command: /usr/syno/sbin/synoupgrade --check
      register: update_check
      ignore_errors: true
      changed_when: false

    - name: Determine if there is more than the check string in the output
      set_fact:
        more_than_check_string: "{{ update_check.stdout_lines | length > 1 }}"
      when: update_check.stdout is search("UPGRADE_CHECKNEWDSM")

    - name: Start the update if more information is present
      command: /usr/syno/sbin/synoupgrade --start-force
      when: more_than_check_string | default(false) | bool
      register: update_started
      ignore_errors: true

    - name: Wait for Synology to restart (if it updated)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 600
      when: update_started is defined and update_started.changed