---
- name: Update and Restart Synology NAS
  hosts: all
  become: true
  vars:
    ansible_scp_if_ssh: true  # Use SCP instead of SFTP to avoid transfer errors
  tasks:

    - name: Retrieve list of iSCSI sessions
      command: iscsiadm -m session
      register: iscsi_sessions
      ignore_errors: true
      changed_when: false

    - name: Disconnect iSCSI LUNs
      command: iscsiadm -m node -u
      when: iscsi_sessions.stdout != "" and iscsi_sessions.rc == 0
      register: lun_disconnect
      failed_when: lun_disconnect.rc not in [0, 21] # 21 may indicate no sessions found

    - name: Check for updates
      command: /usr/syno/sbin/synoupgrade --check
      register: update_check
      changed_when: false
      failed_when: update_check.rc not in [0, 255]  # 255 may indicate no update available

    - name: Determine if an update is available
      set_fact:
        update_available: "{{ 'Available update' in update_check.stdout }}"
      when: update_check.rc == 0

    - name: Download the update if available
      command: /usr/syno/sbin/synoupgrade --download
      when: update_available | default(false) | bool
      register: update_download
      changed_when: "'New update has been downloaded' in update_download.stdout"

    - name: Start the update if downloaded
      command: /usr/syno/sbin/synoupgrade --start
      when: update_download is defined and update_download.changed
      register: update_start
      changed_when: "'Start DSM update' in update_start.stdout"
      async: 0
      poll: 0
      ignore_errors: true