---
- name: Update WSUS Server
  hosts: all
  gather_facts: no

  tasks:
  - name: Run PowerShell Script to approve updates on WSUS
    win_shell: |
      $wsus = Get-WsusServer -Name "CLANDI-WSUS" -PortNumber 8530
      $updates = $wsus.GetUpdates() | Where-Object {$_.IsApproved -eq $false}
      $targetGroup = $wsus.GetComputerTargetGroups() | Where-Object {$_.Name -eq "All Computers"}
      foreach ($update in $updates) {
        $update.Approve('Install', $targetGroup)
      }
    register: shell_output

  - name: Show output
    debug:
      var: shell_output.stdout_lines